app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.PostCreate.as_view(), name='post_create'),
]

app2/urls.py
from django.urls import path
from . import views

app_name = 'app2'

urlpatterns = [
    path('', views.PostCreate.as_view(), name='post_create'),
    path('api/category/get/', views.ajax_get_category, name='ajax_get_category')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('app2/', include('app2.urls')),
]

app/models.py
from django.db import models


class ParentCategory(models.Model):
    name = models.CharField('親カテゴリ名', max_length=255)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=255)
    parent = models.ForeignKey(ParentCategory, verbose_name='親カテゴリ', on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField('タイトル', max_length=255)
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)

    def __str__(self):
        return self.title

app2/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms
from .models import Post, ParentCategory


class PostCreateForm(forms.ModelForm):
    # 親カテゴリの選択欄がないと絞り込めないので、定義する。
    parent_category = forms.ModelChoiceField(
        label='親カテゴリ',
        queryset=ParentCategory.objects,
        required=False
    )

    class Meta:
        model = Post
        fields = '__all__'

    field_order = ('title', 'parent_category', 'category')

app/views.py
from django.views import generic
from .forms import PostCreateForm
from .models import Post, ParentCategory


class PostCreate(generic.CreateView):
    model = Post
    form_class = PostCreateForm
    success_url = '/'  # reverse_lazy等のほうが良い。これは手抜き

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['parentcategory_list'] = ParentCategory.objects.all()
        return context

app2/views.py
from django.http import JsonResponse
from django.views import generic
from app.forms import PostCreateForm
from app.models import Post, Category


class PostCreate(generic.CreateView):
    template_name = 'app2/post_form.html'
    model = Post
    form_class = PostCreateForm
    success_url = '/'  # reverse_lazy等のほうが良い。これは手抜き


def ajax_get_category(request):
    pk = request.GET.get('pk')
    # pkパラメータがない、もしくはpk=空文字列だった場合は全カテゴリを返しておく。
    if not pk:
        category_list = Category.objects.all()

    # pkがあれば、そのpkでカテゴリを絞り込む
    else:
        category_list = Category.objects.filter(parent__pk=pk)

    # [ {'name': 'サッカー', 'pk': '3'}, {...}, {...} ] という感じのリストになる。
    category_list = [{'pk': category.pk, 'name': category.name} for category in category_list]

    # JSONで返す。
    return JsonResponse({'categoryList': category_list})

app/templates/app/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>親カテゴリを選択すると、子カテゴリが絞り込まれる</title>
  </head>
  <body>
    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
  </body>
</html>

app/templates/app/post_form.html
{% extends 'app/base.html' %}
{% block content %}
    <form action="" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>
{% endblock %}

{% block extrajs %}
    <script>
        const parentCategoryElement = $('#id_parent_category');
        const categoryElement = $('#id_category');
        const categories = {
            {% for parent in parentcategory_list %}
                '{{ parent.pk }}': [
                    {% for category in parent.category_set.all %}
                        {
                            'pk': '{{ category.pk }}',
                            'name': '{{ category.name }}'
                        },
                    {% endfor %}
                ],
            {% endfor %}
        };


        const changeCategory = (select) => {
            // 子カテゴリの選択欄を空にする。
            categoryElement.children().remove();

            // 選択した親カテゴリに紐づく子カテゴリの一覧を取得する。
            const parentId = parentCategoryElement.val();
            const categoryList = categories[parentId];

            // 子カテゴリの選択肢を作成・追加。
            for (const category of categoryList) {
                const option = $('<option>');
                option.val(category['pk']);
                option.text(category['name']);
                categoryElement.append(option);
            }

            // 指定があれば、そのカテゴリを選択する
            if (select !== undefined) {
                categoryElement.val(select);
            }
        };


        $('#id_parent_category').on('change', () => {
            changeCategory();
        });


        // 入力値に問題があって再表示された場合、ページ表示時点で小カテゴリが絞り込まれるようにする
        if (parentCategoryElement.val()) {
            const selectedCategory = categoryElement.val();
            changeCategory(selectedCategory);
        }

    </script>
{% endblock %}


app2/templates/app2/post_form.html
{% extends 'app/base.html' %}
{% block content %}
    <form action="" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>
{% endblock %}

{% block extrajs %}
    <script>
        const parentCategoryElement = document.getElementById('id_parent_category');
        const categoryElement = document.getElementById('id_category');

        const changeCategory = (select) => {
            // 子カテゴリの選択欄を空にする。
            categoryElement.innerHTML = '';

            const pk = parentCategoryElement[parentCategoryElement.selectedIndex].value;
            const url = `{% url 'app2:ajax_get_category' %}?pk=${pk}`;

            fetch(url)
                .then(response => {
                    return response.json();
                })
                .then(response => {
                    for (const category of response.categoryList) {
                        const option = document.createElement('option');
                        option.value = category.pk;
                        option.innerHTML = category.name;
                        categoryElement.add(option);
                    }

                    if (select !== undefined) {
                        for (let i = 0, len = categoryElement.length; i < len; i++) {
                            const option = categoryElement[i];
                            if (option.value === select) {
                                option.selected = true;
                            }
                        }
                    }

                })
                .catch(error => {
                    console.log(error)
                });
        };

        parentCategoryElement.addEventListener('change', () => {
            changeCategory();
        });

        // 入力値に問題があって再表示された場合、ページ表示時点で小カテゴリが絞り込まれるようにする
        if (parentCategoryElement[parentCategoryElement.selectedIndex].value) {
            const selectedCategory = categoryElement[categoryElement.selectedIndex].value;
            changeCategory(selectedCategory);
        }


        /*
            // jQueryでやる例
            const parentCategoryElement = $('#id_parent_category');
            const categoryElement = $('#id_category');

            const changeCategory = (select) => {
                // 子カテゴリの選択欄を空にする。
                categoryElement.children().remove();

                $.ajax({
                    url: '{% url 'app2:ajax_get_category' %}',
                    type: 'GET',
                    data: {
                        'pk': parentCategoryElement.val(),
                    }
                }).done(response => {
                    // 子カテゴリの選択肢を作成・追加。
                    for (const category of response.categoryList) {
                        const option = $('<option>');
                        option.val(category['pk']);
                        option.text(category['name']);
                        categoryElement.append(option);
                    }

                    // 指定があれば、そのカテゴリを選択する
                    if (select !== undefined) {
                        categoryElement.val(select);
                    }

                });
            };

            parentCategoryElement.on('change', () => {
                changeCategory();
            });

            // 入力値に問題があって再表示された場合、ページ表示時点で小カテゴリが絞り込まれるようにする
            if (parentCategoryElement.val()) {
                const selectedCategory = categoryElement.val();
                changeCategory(selectedCategory);
            }
         */
    </script>
{% endblock %}
